---
#- name: Update
#  become: true
#  apt:
#    update_cache: true

- name: Install vsftpd
  become: true
  package:
    name: vsftpd
    state: latest

- name: Add config
  become: true
  template: 
    src: /home/mordgren/sf661/vsftpd/vsftpd/templates/conf.j2
    dest: /etc/vsftpd.conf

- name: Restart service
  become: true
  ansible.builtin.shell: systemctl restart vsftpd.service
